# Generated by Django 4.0.2 on 2022-04-26 10:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), size=5)),
                ('hobbies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), size=5)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('net_worth', models.FloatField()),
            ],
        ),
    ]
