# Generated by Django 4.0.2 on 2022-04-28 02:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_user_profile_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_profile',
            new_name='UserProfile',
        ),
    ]
