# Generated by Django 4.0.2 on 2022-05-03 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_alter_userbudget_created_alter_userbudget_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbudget',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='userbudget',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
