# Generated by Django 4.0.2 on 2022-05-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_userbudget_deleted_remove_userprofile_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='advisor',
            field=models.BooleanField(default=False),
        ),
    ]
