# Generated by Django 4.0.2 on 2022-05-06 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_advisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbudget',
            old_name='budget',
            new_name='amount',
        ),
    ]
